backend:
  name: github
  repo: faizulho/vuepress-deploy
  branch: master

public_folder: ".vuepress/public/"
media_folder: ".vuepress/dist/assets/img"

media_library:
  name: cloudinary
  config:
    cloud_name: sgmelayu
    api_key: 492781113816819
    
collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

