backend:
  name: github
  repo: faizulho/vuepress-deploy
  branch: master

public_folder: ".vuepress/public/"
media_folder: ".vuepress/public/assets/img"

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

